run:
  seeds_per_iter: 100
  iterations: 1
  max_new_tokens: 64
  temperature: 0.7

models:
  target_model_name: "meta-llama/Llama-2-7b-chat-hf"

paths:
  runs_dir: "runs"
  seeds_path: "src/storage/seeds.jsonl"
