run:
  seeds_per_iter: 100       # server will override to the prepared count so ALL are processed
  iterations: 1
  max_new_tokens: 64
  temperature: 0.7

models:
  target_model_name: "google/flan-t5-small"

paths:
  runs_dir: "runs"
  seeds_path: "src/storage/seeds.jsonl"
